services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mysql-db
    networks:
      - test-net
    entrypoint: >
      sh -c "echo 'Waiting 10 seconds for MySQL...' &&
             sleep 10 &&
             python dbInit.py &&
             gunicorn -w 4 -k uvicorn.workers.UvicornWorker -b 0.0.0.0:8080 baseApi:app"
    
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - test-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  test-net:
    driver: bridge

volumes:
  mysql-data: