name: Build and Push Docker Image

on:
  push:
    branches:
      - main # or your deployment branch
  workflow_dispatch: # allows manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      IMAGE_NAME: ghcr.io/${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase image name
        id: prep
        run: |
          IMAGE_NAME_LOWER=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME_LOWER=$IMAGE_NAME_LOWER" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME_LOWER/myapp:$IMAGE_TAG .

      # Optional: Run container with secrets for testing
      - name: Run container with injected secrets (test)
        run: |
          docker run --rm \
            -e DB_HOST \
            -e DB_USER \
            -e DB_PASSWORD \
            -e DB_PORT \
            -e DB_NAME \
            ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/myapp:${{ github.sha }}
