name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DB_HOST: mysql.test-net
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_PORT: 3306
      DB_NAME: testdb

      APP_URL: http://api-test.test-net:8080
      APP_BASE: PLACE_HOLDER
      CLAIM_PATH: PLACE_HOLDER
      IDP_ID: PLACE_HOLDER
      IDP_SECRET: PLACE_HOLDER
      IDP_AUTHORIZATION_ENDPOINT: PLACE_HOLDER
      IDP_TOKEN_ENDPOINT: PLACE_HOLDER
      IDP_INTROSPECTION_ENDPOINT: PLACE_HOLDER


      IMAGE_NAME: ghcr.io/${{ github.repository }}
      IMAGE_TAG: base-implementation

    steps:
      # Necessary as I need to convert the image name to lower case, cause linux reasons
      - name: Set lowercase image name
        id: prep
        run: |
          IMAGE_NAME_LOWER=$(echo "${IMAGE_NAME}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME_LOWER=$IMAGE_NAME_LOWER" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME_LOWER/myapp:$IMAGE_TAG .

      # Need to have the api and mysql containers on the same network
      - name: Create Docker network
        run: docker network create test-net

      #Starting my db for testing on the shared network
      - name: Run MySQL container
        run: |
          docker run -d --name mysql --hostname mysql --network test-net -p 3306:3306\
            -e MYSQL_ROOT_PASSWORD=$DB_PASSWORD \
            -e MYSQL_DATABASE=$DB_NAME \
            -e MYSQL_USER=$DB_USER \
            -e MYSQL_PASSWORD=$DB_PASSWORD \
            mysql:8.0

      # Need to wait until I can contact the mysql container
      - name: Wait for MySQL container to be ready
        run: |
          for i in {1..30}; do
            if docker exec mysql mysqladmin ping -h localhost --silent; then
              echo "MySQL is ready"
              exit 0
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

          echo "MySQL container is unreachable"
          exit 1

      # Ensuring the MySQL server has time to start up in the container
      - name: Giving the MySQL server time to boot
        run: |
          sleep 20

      # Running the app for testing
      - name: Run app container connected to network
        run: |
          docker run -d --name api-test --network test-net \
            -e DB_HOST=$DB_HOST \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_PORT=$DB_PORT \
            -e DB_NAME=$DB_NAME \
            -e APP_URL=$APP_URL \
            -e APP_BASE=$APP_BASE \
            -e CLAIM_PATH=$CLAIM_PATH \
            -e IDP_ID=$IDP_ID \
            -e IDP_SECRET=$IDP_SECRET \
            -e IDP_AUTHORIZATION_ENDPOINT=$IDP_AUTHORIZATION_ENDPOINT \
            -e IDP_INTROSPECTION_ENDPOINT=$IDP_INTROSPECTION_ENDPOINT \
            -e IDP_TOKEN_ENDPOINT=$IDP_TOKEN_ENDPOINT \
            $IMAGE_NAME_LOWER/myapp:$IMAGE_TAG \

      # For testing purposes mainly, the container network has been in question during testing
      - name: Log to see if both containers are on the network
        run: |
          docker network inspect test-net

      # Waiting for the api to respond with the landing page
      - name: Wait for the API to be ready
        run: |
          for i in {1..5}; do
            if docker run --rm --network test-net curlimages/curl:latest \
                curl -s --fail $APP_URL; then
              echo -e "/nAPI is ready"
              exit 0
            fi
            echo "Waiting for API to be ready..."
            sleep 3
          done

          echo "The API is unreachable"
          exit 1

      # Giving time to the api to init the db
      - name: Giving the api time to init the db
        run: |
          sleep 20


      # Creating a container that will run the tests
      - name: Run tests inside container
        run: |
          docker build -t test-runner -f- . <<EOF
          FROM python:3.11-slim
          WORKDIR /app
          COPY . .
          RUN pip install --upgrade pip && \
              pip install -r requirements.txt && \
              pip install pytest mysql-connector-python
          CMD ["pytest", "tests"]
          EOF

          docker run --rm --name test-runner --network test-net \
            -e DB_HOST=$DB_HOST \
            -e DB_USER=$DB_USER \
            -e DB_PASSWORD=$DB_PASSWORD \
            -e DB_PORT=$DB_PORT \
            -e DB_NAME=$DB_NAME \
            -e APP_URL=APP_URL \
            test-runner

      # Stopping the app container, cause we are nice
      - name: Stop app container
        if: always()
        run:
          docker stop api-test || true

      # Stopping the mysql container as well for same reasons
      - name: Stop mysql container
        if: always()
        run: docker stop mysql || true

      # Getting the api logs for later
      - name: Debug API container logs
        if: always()
        run: docker logs api-test || true

      # Getting the db logs for later
      - name: Debug mysql container logs
        if: always()
        run: docker logs mysql || true

      # Celebrating a completed run with a new docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME_LOWER/myapp:$IMAGE_TAG
